"""Per-page SEO values. Titles are unique (fixes duplicate-title problem)."""

# faq: optional list of (question, answer) tuples for FAQPage schema.
FAQ_HOME = [
    ("Which areas does DreamFiber cover?",
     "DreamFiber provides fiber broadband, IPTV and OTT in Chakan and Chakan MIDC, with service since 2006."),
    ("How fast is installation?",
     "In most serviceable areas of Chakan we install within 24-48 hours of feasibility confirmation."),
    ("Do you provide lease lines for business?",
     "Yes. DreamFiber offers dedicated lease lines and business broadband across Chakan MIDC."),
    ("Are OTT apps included with broadband?",
     "Yes, we offer Broadband + OTT bundles that include premium OTT subscriptions."),
]

PAGES = {
    "index.html": {
        "title": "DreamFiber | Best WiFi & Fiber Broadband in Chakan (Since 2006)",
        "description": "DreamFiber offers high-speed fiber broadband, IPTV and OTT bundles in Chakan & Chakan MIDC. Trusted internet & cable since 2006. Get WiFi near you today.",
        "path": "/",
        "breadcrumb": [("Home", "/")],
        "faq": FAQ_HOME,
    },
    "broadband.html": {
        "title": "Home Broadband Plans in Chakan | DreamFiber WiFi",
        "description": "Affordable home broadband and WiFi plans in Chakan from DreamFiber. High-speed fiber internet with quick installation and local support.",
        "path": "/broadband.html",
        "breadcrumb": [("Home", "/"), ("Home Broadband", "/broadband.html")],
        "faq": None,
    },
    "broadband-ott.html": {
        "title": "Broadband + OTT Bundles in Chakan | DreamFiber",
        "description": "Get fiber broadband bundled with premium OTT apps in Chakan from DreamFiber. One plan for fast internet and your favourite streaming.",
        "path": "/broadband-ott.html",
        "breadcrumb": [("Home", "/"), ("Broadband + OTT", "/broadband-ott.html")],
        "faq": None,
    },
    "ott.html": {
        "title": "Premium OTT Bundles (Netflix, Prime & more) | DreamFiber",
        "description": "Add premium OTT subscriptions to your DreamFiber connection in Chakan. Stream more for less with bundled OTT packs.",
        "path": "/ott.html",
        "breadcrumb": [("Home", "/"), ("OTT", "/ott.html")],
        "faq": None,
    },
    "iptv.html": {
        "title": "IPTV Plans & Channels in Chakan | DreamFiber",
        "description": "DreamFiber IPTV brings live TV channels over fiber in Chakan & Chakan MIDC. Crisp picture, reliable streaming and local support.",
        "path": "/iptv.html",
        "breadcrumb": [("Home", "/"), ("IPTV", "/iptv.html")],
        "faq": None,
    },
    "enterprise-solution.html": {
        "title": "Lease Line & Business Internet in Chakan MIDC | DreamFiber",
        "description": "Dedicated lease lines and business broadband for offices and factories in Chakan MIDC. Enterprise-grade uptime from DreamFiber since 2006.",
        "path": "/enterprise-solution.html",
        "breadcrumb": [("Home", "/"), ("Business / Lease Line", "/enterprise-solution.html")],
        "faq": None,
    },
    "services.html": {
        "title": "Internet, IPTV & OTT Plans in Chakan | DreamFiber",
        "description": "Browse all DreamFiber plans in Chakan: home broadband, business lease lines, IPTV and OTT bundles. Best internet for home and business.",
        "path": "/services.html",
        "breadcrumb": [("Home", "/"), ("Plans & Services", "/services.html")],
        "faq": None,
    },
    "about.html": {
        "title": "About DreamFiber | Internet & Cable in Chakan Since 2006",
        "description": "DreamFiber (Dream Cable and Internet Services Pvt. Ltd.) has provided internet and cable TV in Chakan since 2006. Learn about our local service.",
        "path": "/about.html",
        "breadcrumb": [("Home", "/"), ("About", "/about.html")],
        "faq": None,
    },
    "contact.html": {
        "title": "Contact DreamFiber | WiFi & Lease Line in Chakan",
        "description": "Contact DreamFiber for new WiFi, broadband, IPTV or lease line in Chakan & Chakan MIDC. Call or WhatsApp for a quick feasibility check.",
        "path": "/contact.html",
        "breadcrumb": [("Home", "/"), ("Contact", "/contact.html")],
        "faq": None,
    },
    "blog.html": {
        "title": "Blog | DreamFiber - Internet, IPTV & OTT Updates",
        "description": "Stay updated with DreamFiber blog. Get the latest on fiber broadband, IPTV, OTT bundles, and internet tips for Chakan & Chakan MIDC.",
        "path": "/blog.html",
        "breadcrumb": [("Home", "/"), ("Blog", "/blog.html")],
        "faq": None,
    },
    "faq.html": {
        "title": "FAQs | DreamFiber - Internet, IPTV & OTT",
        "description": "Frequently Asked Questions about DreamFiber fiber broadband, IPTV, OTT bundles, business leased lines, and support in Chakan & Chakan MIDC.",
        "path": "/faq.html",
        "breadcrumb": [("Home", "/"), ("FAQs", "/faq.html")],
        "faq": None,
    },
    "blog-posts/guest-wifi-small-business.html": {
        "title": "Guest Wi-Fi Setup for Small Business | DreamFiber",
        "description": "Learn how to set up a secure guest Wi-Fi network for your small business. Protect your POS system and customer data with DreamFiber.",
        "path": "/blog-posts/guest-wifi-small-business.html",
        "breadcrumb": [("Home", "/"), ("Blog", "/blog.html"), ("Guest Wi-Fi", "/blog-posts/guest-wifi-small-business.html")],
        "faq": None,
    },
    "blog-posts/wifi-7-future.html": {
        "title": "Wi-Fi 7 Features & Future of Internet | DreamFiber",
        "description": "Wi-Fi 7 (802.11be) is here. Learn about 320 MHz channels, Multi-Link Operation, and 4K QAM. Future-proof your network with DreamFiber.",
        "path": "/blog-posts/wifi-7-future.html",
        "breadcrumb": [("Home", "/"), ("Blog", "/blog.html"), ("Wi-Fi 7 Future", "/blog-posts/wifi-7-future.html")],
        "faq": None,
    },
    "blog-posts/iptv-setup-guide.html": {
        "title": "IPTV Setup Guide for Home | DreamFiber",
        "description": "Step-by-step guide to setting up IPTV at home. From choosing the right internet plan to configuring your smart TV or IPTV box with DreamFiber.",
        "path": "/blog-posts/iptv-setup-guide.html",
        "breadcrumb": [("Home", "/"), ("Blog", "/blog.html"), ("IPTV Setup", "/blog-posts/iptv-setup-guide.html")],
        "faq": None,
    },
    "blog-posts/iptv-channels-guide.html": {
        "title": "IPTV vs Traditional Cable TV | DreamFiber",
        "description": "Compare IPTV vs traditional cable TV. Learn why IPTV is cheaper, more reliable, and offers more features. Switch with DreamFiber today.",
        "path": "/blog-posts/iptv-channels-guide.html",
        "breadcrumb": [("Home", "/"), ("Blog", "/blog.html"), ("IPTV vs Cable", "/blog-posts/iptv-channels-guide.html")],
        "faq": None,
    },
    "blog-posts/4k-streaming-speed-guide.html": {
        "title": "Internet Speed for 4K OTT Streaming | DreamFiber",
        "description": "Find out the real internet speed needed for 4K streaming on Netflix, Prime Video, Disney+ Hotstar. Calculate your household's bandwidth with DreamFiber.",
        "path": "/blog-posts/4k-streaming-speed-guide.html",
        "breadcrumb": [("Home", "/"), ("Blog", "/blog.html"), ("4K Streaming Guide", "/blog-posts/4k-streaming-speed-guide.html")],
        "faq": None,
    },
    "blog-posts/ott-bundle-savings.html": {
        "title": "Bundled Broadband & OTT Subscriptions Guide | DreamFiber",
        "description": "Save money with bundled broadband and OTT subscriptions. Learn how DreamFiber bundles Netflix, Prime Video, Disney+ with high-speed internet.",
        "path": "/blog-posts/ott-bundle-savings.html",
        "breadcrumb": [("Home", "/"), ("Blog", "/blog.html"), ("OTT Bundle Guide", "/blog-posts/ott-bundle-savings.html")],
        "faq": None,
    },
    "blog-posts/internet-security-tips.html": {
        "title": "Secure Your Home Wi-Fi Network from Hackers | DreamFiber",
        "description": "Protect your home Wi-Fi from hackers. Learn about WPA3 encryption, guest networks, and router security tips from DreamFiber.",
        "path": "/blog-posts/internet-security-tips.html",
        "breadcrumb": [("Home", "/"), ("Blog", "/blog.html"), ("Wi-Fi Security", "/blog-posts/internet-security-tips.html")],
        "faq": None,
    },
    "blog-posts/boost-wifi-signal.html": {
        "title": "Boost Home Wi-Fi Signal & Eliminate Dead Zones | DreamFiber",
        "description": "Eliminate Wi-Fi dead zones with these tips. Learn about Mesh Wi-Fi, extenders, band switching, and channel optimization from DreamFiber.",
        "path": "/blog-posts/boost-wifi-signal.html",
        "breadcrumb": [("Home", "/"), ("Blog", "/blog.html"), ("Boost Wi-Fi", "/blog-posts/boost-wifi-signal.html")],
        "faq": None,
    },
    "blog-posts/wifi-speed-optimization.html": {
        "title": "Router Placement Tips for Maximum Wi-Fi Speed | DreamFiber",
        "description": "Improve your Wi-Fi speed with optimal router placement. Learn 5 tips including central positioning, elevation, and antenna adjustments from DreamFiber.",
        "path": "/blog-posts/wifi-speed-optimization.html",
        "breadcrumb": [("Home", "/"), ("Blog", "/blog.html"), ("Router Tips", "/blog-posts/wifi-speed-optimization.html")],
        "faq": None,
    },
    "blog-posts/fiber-internet-guide.html": {
        "title": "Fiber Optic vs Regular Broadband Comparison | DreamFiber",
        "description": "Compare fiber optic internet vs regular broadband (ADSL/VDSL). Learn about speed, reliability, and latency. Check fiber availability with DreamFiber.",
        "path": "/blog-posts/fiber-internet-guide.html",
        "breadcrumb": [("Home", "/"), ("Blog", "/blog.html"), ("Fiber vs Broadband", "/blog-posts/fiber-internet-guide.html")],
        "faq": None,
    },
    "blog-posts/home-broadband-guide.html": {
        "title": "How to Choose the Best Home Broadband Plan | DreamFiber",
        "description": "Learn how to choose the best home broadband plan. Speed guide, fiber vs copper, unlimited data, and router tips from DreamFiber.",
        "path": "/blog-posts/home-broadband-guide.html",
        "breadcrumb": [("Home", "/"), ("Blog", "/blog.html"), ("Home Broadband Guide", "/blog-posts/home-broadband-guide.html")],
        "faq": None,
    },
    "blog-posts/cost-of-downtime.html": {
        "title": "True Cost of Internet Downtime for Business | DreamFiber",
        "description": "Calculate the true cost of internet downtime for your business. Learn how SLAs, redundancy, and reliable broadband from DreamFiber protect you.",
        "path": "/blog-posts/cost-of-downtime.html",
        "breadcrumb": [("Home", "/"), ("Blog", "/blog.html"), ("Cost of Downtime", "/blog-posts/cost-of-downtime.html")],
        "faq": None,
    },
    "blog-posts/dedicated-broadband-reasons.html": {
        "title": "5 Reasons Your Business Needs Dedicated Broadband | DreamFiber",
        "description": "Discover 5 reasons your growing business needs dedicated broadband: guaranteed speeds, symmetric uploads, security, SLAs, and scalability from DreamFiber.",
        "path": "/blog-posts/dedicated-broadband-reasons.html",
        "breadcrumb": [("Home", "/"), ("Blog", "/blog.html"), ("Dedicated Broadband", "/blog-posts/dedicated-broadband-reasons.html")],
        "faq": None,
    },
    "blog-posts/internet-leased-line-guide.html": {
        "title": "What is an Internet Leased Line (ILL) | DreamFiber",
        "description": "Learn what an Internet Leased Line (ILL) is and whether your office needs one. Dedicated bandwidth, symmetric speeds, and SLAs from DreamFiber.",
        "path": "/blog-posts/internet-leased-line-guide.html",
        "breadcrumb": [("Home", "/"), ("Blog", "/blog.html"), ("ILL Guide", "/blog-posts/internet-leased-line-guide.html")],
        "faq": None,
    },
    "blog-posts/business-broadband-chakan.html": {
        "title": "Leased Line vs Business Broadband Comparison | DreamFiber",
        "description": "Compare leased line vs business broadband. Learn about dedicated vs shared connections, symmetric speeds, and SLAs. Choose the right plan with DreamFiber.",
        "path": "/blog-posts/business-broadband-chakan.html",
        "breadcrumb": [("Home", "/"), ("Blog", "/blog.html"), ("Leased Line vs Broadband", "/blog-posts/business-broadband-chakan.html")],
        "faq": None,
    },
}

OG_IMAGE = "/assets/hero_bg.png"  # TODO(owner): swap for a 1200x630 share image if available.
